#!/usr/bin/env python3
"""Interactive setup: personalize this workflow in ~2 minutes.

Asks a few plain questions, then:
  - writes config.yaml (your team, product, goals, voice knobs)
  - fills the "About you" section in VOICE.md
  - fills the "Your goals" section in PLAYBOOK.md

Run:  python3 setup.py
Re-runnable — it only rewrites the marked SETUP sections, never your edits.
"""

from __future__ import annotations

import os
import shutil

ROOT = os.path.dirname(os.path.abspath(__file__))


def ask(prompt: str, default: str = "") -> str:
    hint = f" [{default}]" if default else ""
    ans = input(f"{prompt}{hint}: ").strip()
    return ans or default


def ask_choice(prompt: str, options: list, default: int = 1) -> str:
    print(prompt)
    for i, o in enumerate(options, 1):
        print(f"  {i}) {o}")
    while True:
        ans = input(f"Choose [{default}]: ").strip() or str(default)
        if ans.isdigit() and 1 <= int(ans) <= len(options):
            return options[int(ans) - 1]
        print("Pick a number from the list.")


def ask_multiline(prompt: str) -> str:
    print(prompt + " (Enter on an empty line to finish, or skip)")
    lines = []
    while True:
        line = input()
        if not line.strip():
            break
        lines.append(line.rstrip())
    return "\n".join(lines).strip()


def yaml_str(v: str) -> str:
    return '"%s"' % v.replace('"', "'")


def write_config(a: dict) -> None:
    team_lines = []
    for name, aid in a["team"]:
        team_lines.append(f'  - name: {yaml_str(name)}')
        if aid:
            team_lines.append(f'    heyreach_account_id: {aid}')
    body = f"""# Generated by setup.py — edit freely, or re-run setup.py.
team:
{chr(10).join(team_lines) if team_lines else '  []'}

product:
  name: {yaml_str(a['product'])}
  one_liner: {yaml_str(a['one_liner'])}
  meeting_link: {yaml_str(a['meeting_link'])}
  docs_url: {yaml_str(a['docs_url'])}

goals:
{chr(10).join('  - ' + yaml_str(g) for g in a['goals'])}

voice:
  tone: {yaml_str(a['tone'])}
  max_sentences: {a['max_sentences']}
  emojis: {"true" if a["emojis"] else "false"}
"""
    open(os.path.join(ROOT, "config.yaml"), "w").write(body)


def patch_section(path: str, section: str) -> None:
    """Replace content between <!-- SETUP:START --> and <!-- SETUP:END -->."""
    start, end = "<!-- SETUP:START -->", "<!-- SETUP:END -->"
    text = open(path).read()
    if start not in text or end not in text:
        print(f"warn: no SETUP markers in {os.path.basename(path)}, skipped")
        return
    before, rest = text.split(start, 1)
    _, after = rest.split(end, 1)
    open(path, "w").write(before + start + "\n" + section.strip() + "\n" + end + after)


def main() -> None:
    print("=== heyreach-inbox-digest setup ===\n")

    product = ask("Product name", "HeyReach")
    one_liner = ask("One-liner: what does it do?",
                    "LinkedIn outreach automation")
    name = ask("Your name (as it appears on your HeyReach sender account)")
    account_id = ask("Your HeyReach LinkedIn account ID (number, optional)")
    mates = ask("Teammates who also reply (comma-separated, optional)")
    team = []
    if name:
        team.append((name, account_id))
    team += [(m.strip(), "") for m in mates.split(",") if m.strip()]

    meeting_link = ask("Meeting booking link for CTAs (optional)")
    docs_url = ask("Help docs URL (optional)")
    primary = ask_choice("What's the #1 outcome you want from a reply?",
                         ["Book a meeting", "Sell an upgrade", "Resolve support fast"],
                         default=1)
    goals = [primary]
    for g in ["Book a meeting", "Sell an upgrade", "Resolve support fast"]:
        if g != primary:
            goals.append(g)
    tone = ask_choice("How should replies sound? (direct = Hormozi-style: plain, confident, no fluff)",
                      ["direct", "casual", "professional", "playful"], default=1)
    max_sentences = ask("Max sentences per reply", "4")
    emojis = ask("Emojis ok? (y/n)", "n").lower().startswith("y")
    example = ask_multiline("Paste one reply you're proud of (so drafts match your voice)")

    answers = {
        "product": product, "one_liner": one_liner, "team": team,
        "meeting_link": meeting_link, "docs_url": docs_url,
        "goals": [g.lower() for g in goals], "tone": tone,
        "max_sentences": max_sentences if max_sentences.isdigit() else "4",
        "emojis": emojis, "example": example,
    }
    write_config(answers)

    team_names = ", ".join(n for n, _ in team) or "—"
    voice_section = f"""## About you (generated by `setup.py` — re-run it to update)

- **Team:** {team_names}
- **Product:** {product} — {one_liner}
- **Tone:** {tone}. Keep replies to ~{answers['max_sentences']} sentences, \
{"emojis ok" if emojis else "no emojis unless the lead used one"}. \
First person as the sender, never "the team".
- **Meeting link for CTAs:** {meeting_link or "—"}
- **Example reply in your voice:**
> {(example.replace(chr(10), chr(10) + "> ") if example else "_run setup.py and paste one_")}"""
    patch_section(os.path.join(ROOT, "VOICE.md"), voice_section)

    playbook_section = f"""## Your goals (generated by `setup.py` — re-run it to update)

In priority order:
{chr(10).join(f"{i}. **{g}**" for i, g in enumerate(answers['goals'], 1))}
- **Product:** {product} — {one_liner}
- **Meeting CTA link:** {meeting_link or "—"}
- Triage every thread first (HOT / WARM / SUPPORT / LUKEWARM / NOISE), then aim
  the draft at the highest-priority goal that fits."""
    patch_section(os.path.join(ROOT, "PLAYBOOK.md"), playbook_section)

    print("\nDone! Wrote config.yaml and personalized VOICE.md + PLAYBOOK.md.")
    print("Next: python3 digest.py")


if __name__ == "__main__":
    # Never overwrite an existing config without a backup.
    cfg = os.path.join(ROOT, "config.yaml")
    if os.path.exists(cfg):
        shutil.copy(cfg, cfg + ".bak")
        print(f"(backed up existing config.yaml to config.yaml.bak)")
    main()
